name: FastAPI Train Timetable CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        pip install poetry
        poetry install --with dev

    - name: Lint (flake8, black, isort)
      run: |
        poetry run flake8 app tests
        poetry run black --check app tests
        poetry run isort --check-only app tests

    - name: Run tests with coverage
      run: |
        poetry run coverage run -m pytest
        poetry run coverage report
        poetry run coverage html
        ls -R htmlcov
