name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
      - name: Lint and format all code (including tests)
        run: poetry run autoflake --in-place --remove-all-unused-imports --recursive . && poetry run black .
      - name: Lint with flake8
        continue-on-error: true
        run: poetry run flake8 src/ --config .flake8

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
      - name: Run tests
        run: poetry run pytest
      - name: Run Behave BDD tests
        run: |
          poetry install
          PYTHONPATH=src poetry run behave tests/features/

  docker:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Remove the above step if you don't want to push to DockerHub
      - name: Build Docker image
        run: docker build -t uk-train-timetable .
      # - name: Push Docker image
      #   if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
      #   run: docker push uk-train-timetable

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
      - name: Autoflake, isort, and Black (pre-commit)
        run: poetry run autoflake --in-place --remove-all-unused-imports --recursive . && poetry run isort . && poetry run black .
      - name: Commit changes if needed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --cached --quiet || git commit -m 'style: autoflake, isort, and black formatting [auto]'
          git push || echo 'No changes to commit.'
