name: Deployment Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
      - name: Lint with black
        run: poetry run black --check src/
      - name: Lint with flake8
        run: poetry run flake8 src/ --config .flake8
      - name: Run tests
        run: poetry run pytest
      - name: Build Docker image
        run: docker build -t uk-train-timetable .
      - name: Check Uvicorn ASGI app import
        run: |
          docker run --rm -e PORT=8000 -p 8000:8000 uk-train-timetable uvicorn main:app --host 0.0.0.0 --port 8000 --lifespan=off &
          sleep 10
          curl --fail http://localhost:8000/health
